
// ADD ITEMS TO CART
export const CART_ADD_ITEM = "CART_ADD_ITEM";

// REMOVE ITEMS FROM CART
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";


// SAVE BOOKINGDETAILS
export const CART_SAVE_BOOKING_DETAILS = "CART_SAVE_BOOKING_DETAILS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

// DELETE CART INFO IN LOCAL STORAGE AFTER ORDER PLACED
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
